// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlakDukkaniSinav.Context;

#nullable disable

namespace PlakDukkaniSinav.Data.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20230109113525_Mig1")]
    partial class Mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PlakDukkaniSinav.Class.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adminler");
                });

            modelBuilder.Entity("PlakDukkaniSinav.Class.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AlbumAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CikisTarihi")
                        .HasColumnType("int");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IndirimOrani")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sanatci")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SatisDevamMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Albumler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumAdi = "Back In Black",
                            CikisTarihi = 1980,
                            Fiyat = 600m,
                            IndirimOrani = 0m,
                            Sanatci = "AC/DC",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 2,
                            AlbumAdi = "Hurt",
                            CikisTarihi = 2002,
                            Fiyat = 400m,
                            IndirimOrani = 0.12m,
                            Sanatci = "Johhny Cash",
                            SatisDevamMi = false
                        },
                        new
                        {
                            Id = 3,
                            AlbumAdi = "Hotel California",
                            CikisTarihi = 1976,
                            Fiyat = 599m,
                            IndirimOrani = 0.1m,
                            Sanatci = "Eagles",
                            SatisDevamMi = true
                        },
                        new
                        {
                            Id = 4,
                            AlbumAdi = "Zeytin Yağlı Yaprak Dolması",
                            CikisTarihi = 1995,
                            Fiyat = 200m,
                            IndirimOrani = 0m,
                            Sanatci = "Grup Vitamin",
                            SatisDevamMi = false
                        },
                        new
                        {
                            Id = 5,
                            AlbumAdi = "Neden Saçların Beyazlamış Arkadaş",
                            CikisTarihi = 2005,
                            Fiyat = 250m,
                            IndirimOrani = 0.2m,
                            Sanatci = "Adnan Şenses",
                            SatisDevamMi = false
                        },
                        new
                        {
                            Id = 6,
                            AlbumAdi = "Bombabomba.com",
                            CikisTarihi = 2006,
                            Fiyat = 100m,
                            IndirimOrani = 0.25m,
                            Sanatci = "İsmail YK",
                            SatisDevamMi = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
